# -*- coding: utf-8 -*-
"""Assignment 3 Q1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/181s3l2UwkHaEQYMsK8O5meg1xbNqf2x_
"""

Write a Python function to sum all the numbers in a list.

def sum(numbers):

   total = 0

   for x in numbers:

       total += x

   return total

print(sum((8, 2, 3, 0, 7)))